<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.dao.support.DataAccessUtilsTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2021-06-20T08:13:00" hostname="gankangdembp" time="0.044">
  <properties/>
  <testcase name="withString()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.002"/>
  <testcase name="withInteger()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.002"/>
  <testcase name="exceptionTranslationWithNoTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withDate()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.019"/>
  <testcase name="withLong()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withTooLargeCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.004"/>
  <testcase name="withSameIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withEmptyCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.011"/>
  <testcase name="withEquivalentIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="exceptionTranslationWithTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
